__all__ = [
    "resourcesViewFull",
    "resistancesViewFull",
    "resistancesViewMinimal",
    "rechargeViewFull",
    "rechargeViewMinimal",
    "firepowerViewFull",
    "capacitorViewFull",
    "outgoingViewFull",
    "outgoingViewMinimal",
    "targetingMiscViewMinimal",
    "priceViewFull",
    "priceViewMinimal",
    "dronesViewFull",
]
